// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return desktop;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7yYz4RPqnEVLSEfr83VchZRUtbSKgyRU',
    appId: '1:199407683103:android:1de5d55a6512f6155f772a',
    messagingSenderId: '199407683103',
    projectId: 'com-warraich-petroleum',
    databaseURL:
        'https://com-warraich-petroleum-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'com-warraich-petroleum.firebasestorage.app',
  );

  static const FirebaseOptions desktop = FirebaseOptions(
    apiKey: 'AIzaSyC7yYz4RPqnEVLSEfr83VchZRUtbSKgyRU',
    appId: '1:199407683103:android:1de5d55a6512f6155f772a',
    messagingSenderId: '199407683103',
    projectId: 'com-warraich-petroleum',
    databaseURL:
        'https://com-warraich-petroleum-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'com-warraich-petroleum.firebasestorage.app',
  );
}
